---
- name: Manage BGP & OSPF device MLX1
  hosts: mlx1
  gather_facts: false
  connection: local

  vars:
    cli:
      username: hidayahweb
      password: cisco

  tasks:
    - name: enable ospf
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0
          - exit
          - int lo0
          - ip add 1.1.1.1 255.255.255.255
          - int lo1
          - ip add 2.2.2.2 255.255.255.255
          - exit
          - router bgp 1
          - network 1.1.1.1 mask 255.255.255.255
          - network 2.2.2.2 mask 255.255.255.255

      register: print_output

    -  debug: var=print_output

